M48
; DRILL file {KiCad (6.0.11)} date Fri Feb 20 21:52:22 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-20T21:52:22+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X31.995Y-119.165
X34.495Y-28.765
X103.495Y-28.765
X106.495Y-119.165
T0
M30
