M48
; DRILL file {KiCad (6.0.11)} date Tue Feb 24 14:27:30 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-24T14:27:30+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X31.995Y-119.165
X34.495Y-28.765
X103.495Y-28.765
X106.495Y-119.165
T0
M30
